version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: daarligbilist
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8888

  server:
    image: server
    build:
      dockerfile: Dockerfile.server
      context: .
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - db

  client:
    image: client
    build:
      dockerfile: Dockerfile.client
      context: .
    restart: always
    ports:
      - 8080:80
    depends_on:
      - server
    tty: true
